baseURL = "pasadena15.com"
languageCode = "es-mx"
title = "Pasadena 15 - Despacho de Abogados"
themesDir = "themes"
theme = "hugo-serif-theme"
#theme = "hugo-assembly"

[params]
  author = "Marco Villaseñor"
  description = "Pasadena 15"
  google_analytics_id=""
  google_tag_manager_id = ""

  # banner section (from here on is for assembly theme)
  [params.banner]
    title = "Pasadena 15"
    byline = "Despacho de abogados"

  [params.actions] # CTAs
    enable = true
    register = "Consultas"

  # Navigation section
  [params.nav]
    home = "Inicio"
    services = "Services"
    welcome = "Welcome"
    contact = "Contact Us"

  [params.logo]
    mobile = "images/logo.svg"
    standard  = "images/logo.svg"
    alt = "Serif - A Hugo Business Theme"

  [params.homepage_meta_tags]
    meta_description = "Despacho de abogados."
    meta_og_title = "Pasadena 15"
    meta_og_type = "website"
    meta_og_url = "https://pasadena15.com"
    meta_og_image = "https://pasadena15.com/resources/images/logo.svg"
    meta_og_description = "Pasadena 15 / Despacho de abogados."
    meta_twitter_card = "Pasadena 15 / Despacho de abogados."

  [params.features]
    title = "Otorgamos Asesoría en Derecho"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Quienes Somos"
    url = "/quienes-somos/"
      weight = 1

  [[menu.main]]
    name = "Misión"
    url = "/mision/"
      weight = 2

  [[menu.main]]
    name = "Integrantes"
    url = "/integrantes/"
      weight = 3

  [[menu.main]]
    name = "Consultas"
    url = "/consultas/"
      weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Dirección"
    url = "/direccion/"
      weight = 1

  [[menu.footer]]
    name = "Aviso de Privacidad"
    url = "/aviso-de-privacidad/"
      weight = 2
